name: Everyday Tutor
favicon: null
layout_spectrum: 0.46303775324486196
typography_spectrum: 0.6036922261118889
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#669084'
    - '#85bda2'
    - '#dff0c4'
    - '#dcca9f'
  brandStrength: 0.5403839715290815
  lightness: 0.12292559421621263
  saturation: 0.482898119604215
  rhythmicContrast: 0.6288244500756264
purpose: []
